### ISSUE TITLE
Multiple calls to single endpoint

### ISSUE THREAD

**Issue by sporkins** [Confluex/confluex-mock-http#4]
This may not be a bug.  There may already be a solution.  If you're flow calls the same endpoint multiple times, with different query parameters, how can I mock out each call?

If try this:

mockHttpEndpoint
      .when("/something?a=1")

mockHttpEndpoint
      .when("/something?a=2")

I get a this exception:

java.lang.IllegalArgumentException: No captor mapped to uri: /something
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by mcantrell** [comment]
I'll take a look and see what I turn up :-)

**Comment by mcantrell** [comment]
This is definitely something we want to support in the library. It's going to take a bit of refactoring so I'm going to move it into the next milestone. We're a bit swamped at the moment but I'll get this in and released sometime soon.

**Comment by sporkins** [comment]
Thanks for looking into this.  I appreciate it!

**Comment by rhoegg** [comment]
I am thinking we do it this way:

mockHttpEndpoint.when("/something").withParameterValue("a", "1")
mockHttpEndpoint.when("/something").withParameterValue("a", "2")

**Comment by rhoegg** [comment]
Added this feature to the mock-http-server branch, as part of complex request matching

**Comment by rhoegg** [comment]
merged the branch to master, we can close this when 0.3.0 is released

**Comment by rhoegg** [comment]
0.3.0 went out today!
