### ISSUE TITLE
HTTPS Client Trusted Certificate

### ISSUE THREAD

**Issue by cgorshing** [Confluex/confluex-mock-http#8]
They keystore given does not have a key in the format needed for a client to connect and trust the certificate presented.

I've gotten around this by using https://code.google.com/p/java-use-examples/source/browse/trunk/src/com/aw/ad/util/InstallCert.java (running the HTTPS mocked server first, then passing in localhost:<port>).

The above creates a keystore with the certificate presented by the server. Then by using a connector such as:

``` xml
<https:connector name="httpsConnector">
   <https:tls-client path="C:\path\to\jssecacerts"/>
</https:connector>
```

So I would like to request to already have this in the keystore already a part of the project so the connector could be:

``` xml
<https:connector name="httpsConnector">
   <https:tls-client path="/confluex-mock.keystore" storePassword="confluex"/>
</https:connector>
```

**Comment by mcantrell** [comment]
Thanks Chad. We'll get it updated. For now, you can register the trust manager factory within the Mule connector manually:

``` java
   @Before
    public void startMockHttpServer() throws Exception {
        server = new MockHttpsServer(8081);
        HttpsConnector connector = muleContext.getRegistry().lookupObject(HttpsConnector.class);
        connector.setTrustManagerFactory(MockHttpsServer.getTrustManagerFactory());
    }
```

**Comment by rhoegg** [comment]
The issue is with the algorithm used by the line

``` xml
    <https:tls-client path="/confluex-mock.keystore" storePassword="confluex"/>
```

`confluex-mock.keystore` is already on the classpath, but the Mule code that loads the keystore is not compatible with JKS/SunX509 which is what I used to create the keystore.  My workaround was similar to Mike's, but in a test mule configuration.

``` xml
    <https:connector name="httpsConnector">
        <spring:property name="trustManagerFactory">
            <spring:bean class="com.confluex.mock.http.MockHttpsServer" factory-method="getTrustManagerFactory" />
        </spring:property>
    </https:connector>
```

If you wanted to make a pull request to add a keystore that is compatible with `<https:tls-client />` I would merge it.

**Comment by cgorshing** [comment]
I think Mike's response is better suited for tests as this does not impact any Mule Flows. The only changes need to be in the test itself (which is more ideal to me). I'm hesitant to change up a flow solely for testing (albeit not completely against it).

But going forward I think it is easier to show and document the changes needed in a test, than it is in a test and changes to someones flow.
